app:
  name: nodejs-hello-api
replicaCount: 2
image:
  repository: alx52/nodejs-hello-api
  tag: "0.0.4"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
configMap:
  PORT: "3001"
  LOG_LEVEL: "info"
  AWS_REGION: us-east-1
  AWS_SQS_QUEUE_NAME: /000000000000/minha-fila
  AWS_ENDPOINT_URL: "http://localstack.infra.svc.cluster.local:4566"
  AWS_ACCESS_KEY_ID: your_access_key_id
  AWS_SECRET_ACCESS_KEY: your_secret_access_key
